backend:
  name: github
  repo: StockLogic/StockLogic
  branch: main

media_folder: "content/uploads"
public_folder: "/content/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }
